FROM python:3.12.6-slim

ENV PIPENV_VENV_IN_PROJECT=1

RUN pip install pipenv

RUN useradd -ms /bin/bash myuser

USER myuser

WORKDIR /app

RUN chown -R myuser /app

COPY --chown=myuser:myuser . /app

RUN chmod +x /app/start.sh

RUN pipenv install

CMD sh -c /app/start.sh
